apiVersion: 1

datasources:
  - name: Elasticsearch
    uid: P31C819B24CF3C3C7
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: true
    editable: true

    jsonData:
      index: 'ca-monitor-*'
      timeField: '@timestamp'