# Generated by Django 5.2.8 on 2025-11-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CACertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_cert', models.TextField()),
                ('serial_number', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.TextField()),
                ('certificate_pem', models.TextField()),
                ('serial_number', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
