# Generated by Django 5.2.8 on 2025-11-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cacertificate',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usercertificate',
            name='id',
        ),
        migrations.AddField(
            model_name='cacertificate',
            name='ca_cert_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usercertificate',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
