# Generated by Django 5.2.8 on 2025-11-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0002_remove_cacertificate_id_remove_usercertificate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertificate',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
