# Generated by Django 6.0.3 on 2026-03-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0003_alter_usercertificate_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacertificate',
            name='hash_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='usercertificate',
            name='hash_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
