version: '3.8'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - monitoring
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 | grep -q 'tagline'"]
      interval: 10s
      retries: 10

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: filebeat
    user: root
    volumes:
      - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/logs:ro
    command: filebeat -e --strict.perms=false
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
        # ── SMTP ──────────────────────────────
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=ruicarvalhor13@gmail.com
      - GF_SMTP_PASSWORD=efjg zlqe gfbv rfjd
      - GF_SMTP_FROM_ADDRESS=ruicarvalhor13@gmail.com
      - GF_SMTP_FROM_NAME=Grafana CA Monitor
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
    depends_on:
      - elasticsearch
    networks:
      - monitoring

volumes:
  es_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge